name: Carga de commit exitoso

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mostrar mensaje de éxito
        run: |
          echo "¡Commit exitoso en la rama develop!"
